class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_name': 'Paywave',
      'register': 'Register',
      'login': 'Login',
      'name': 'Name',
      'username': 'Username',
      'phone': 'Phone',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'otp': 'OTP',
      'send_otp': 'Send OTP',
      'resend_otp': 'Resend OTP',
      'verify': 'Verify',
      'continue': 'Continue',
      'dashboard': 'Dashboard',
      'send': 'Send',
      'receive': 'Receive',
      'history': 'History',
      'settings': 'Settings',
      'logout': 'Logout',
      'amount': 'Amount',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'select_receiver': 'Select Receiver',
      'scan_devices': 'Scan Devices',
      'bluetooth': 'Bluetooth',
      'nfc': 'NFC',
      'sms': 'SMS',
      'successful': 'Successful',
      'pending': 'Pending',
      'cancelled': 'Cancelled',
      'transaction_details': 'Transaction Details',
      'timestamp': 'Timestamp',
      'channel': 'Channel',
      'status': 'Status',
      'device_id': 'Device ID',
      'sync_status': 'Sync Status',
      'synced': 'Synced',
      'not_synced': 'Not Synced',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'accent_color': 'Accent Color',
      'biometric': 'Biometric',
      'auto_lock': 'Auto Lock',
      'language': 'Language',
      'online': 'Online',
      'offline': 'Offline',
      'syncing': 'Syncing',
      'last_transaction': 'Last Transaction',
      'no_transactions': 'No transactions yet',
      'payment_successful': 'Payment Successful',
      'payment_failed': 'Payment Failed',
      'payment_cancelled': 'Payment Cancelled',
      'waiting_for_payment': 'Waiting for payment...',
      'scanning': 'Scanning...',
      'connecting': 'Connecting...',
      'sending': 'Sending...',
      'select_role': 'Select Role',
      'sender': 'Sender',
      'receiver': 'Receiver',
      'enter_pin': 'Enter PIN',
      'authenticate': 'Authenticate',
      'biometric_failed': 'Biometric authentication failed',
      'pin_incorrect': 'Incorrect PIN',
      'device_not_found': 'Device not found',
      'connection_failed': 'Connection failed',
      'bluetooth_timeout': 'Bluetooth timeout',
      'nfc_timeout': 'NFC timeout',
      'sms_failed': 'SMS send failed',
      'logout_confirm': 'Are you sure you want to logout?',
      'yes': 'Yes',
      'no': 'No',
    },
    'hi': {
      'app_name': 'पेवेव',
      'register': 'पंजीकरण',
      'login': 'लॉगिन',
      'name': 'नाम',
      'username': 'उपयोगकर्ता नाम',
      'phone': 'फोन',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'otp': 'ओटीपी',
      'send_otp': 'ओटीपी भेजें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'verify': 'सत्यापित करें',
      'continue': 'जारी रखें',
      'dashboard': 'डैशबोर्ड',
      'send': 'भेजें',
      'receive': 'प्राप्त करें',
      'history': 'इतिहास',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'amount': 'राशि',
      'confirm': 'पुष्टि करें',
      'cancel': 'रद्द करें',
      'select_receiver': 'प्राप्तकर्ता चुनें',
      'scan_devices': 'डिवाइस स्कैन करें',
      'bluetooth': 'ब्लूटूथ',
      'nfc': 'एनएफसी',
      'sms': 'एसएमएस',
      'successful': 'सफल',
      'pending': 'लंबित',
      'cancelled': 'रद्द',
      'transaction_details': 'लेनदेन विवरण',
      'timestamp': 'समय',
      'channel': 'चैनल',
      'status': 'स्थिति',
      'device_id': 'डिवाइस आईडी',
      'sync_status': 'सिंक स्थिति',
      'synced': 'सिंक किया गया',
      'not_synced': 'सिंक नहीं किया गया',
      'theme': 'थीम',
      'light': 'लाइट',
      'dark': 'डार्क',
      'accent_color': 'एक्सेंट रंग',
      'biometric': 'बायोमेट्रिक',
      'auto_lock': 'ऑटो लॉक',
      'language': 'भाषा',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन',
      'syncing': 'सिंक हो रहा है',
      'last_transaction': 'अंतिम लेनदेन',
      'no_transactions': 'अभी तक कोई लेनदेन नहीं',
      'payment_successful': 'भुगतान सफल',
      'payment_failed': 'भुगतान विफल',
      'payment_cancelled': 'भुगतान रद्द',
      'waiting_for_payment': 'भुगतान की प्रतीक्षा में...',
      'scanning': 'स्कैन हो रहा है...',
      'connecting': 'कनेक्ट हो रहा है...',
      'sending': 'भेजा जा रहा है...',
      'select_role': 'भूमिका चुनें',
      'sender': 'भेजने वाला',
      'receiver': 'प्राप्तकर्ता',
      'enter_pin': 'पिन दर्ज करें',
      'authenticate': 'प्रमाणित करें',
      'biometric_failed': 'बायोमेट्रिक प्रमाणीकरण विफल',
      'pin_incorrect': 'गलत पिन',
      'device_not_found': 'डिवाइस नहीं मिला',
      'connection_failed': 'कनेक्शन विफल',
      'bluetooth_timeout': 'ब्लूटूथ टाइमआउट',
      'nfc_timeout': 'एनएफसी टाइमआउट',
      'sms_failed': 'एसएमएस भेजना विफल',
      'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'yes': 'हाँ',
      'no': 'नहीं',
    },
  };

  static String translate(String key, String language) {
    return _localizedStrings[language]?[key] ?? key;
  }
}
